#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("A_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("A_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("A_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("A_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("A_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("A_TUSER", 2, hls_in, 3, "axis", "in_data", 1),
	Port_Property("A_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("A_TID", 5, hls_in, 5, "axis", "in_data", 1),
	Port_Property("A_TDEST", 6, hls_in, 6, "axis", "in_data", 1),
	Port_Property("fifo_out_din", 8, hls_out, 7, "ap_fifo", "fifo_data_in", 12),
	Port_Property("fifo_out_full_n", 1, hls_in, 7, "ap_fifo", "fifo_status", 12),
	Port_Property("fifo_out_write", 1, hls_out, 7, "ap_fifo", "fifo_port_we", 12),
	Port_Property("STATUS", 32, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("STATUS_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("COUNTER", 32, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("COUNTER_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "example";
