# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/dma_axis_ip_example/dma_axis_ip_example.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example || ORIG_REF_NAME==dma_axis_ip_example} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_dma_0/dma_axis_ip_example_axi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_axi_dma_0 || ORIG_REF_NAME==dma_axis_ip_example_axi_dma_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_xbar_1/dma_axis_ip_example_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_xbar_1 || ORIG_REF_NAME==dma_axis_ip_example_xbar_1} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_mem_intercon_1_0/dma_axis_ip_example_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_axi_mem_intercon_1_0 || ORIG_REF_NAME==dma_axis_ip_example_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_processing_system7_0_0/dma_axis_ip_example_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_processing_system7_0_0 || ORIG_REF_NAME==dma_axis_ip_example_processing_system7_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_xbar_0/dma_axis_ip_example_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_xbar_0 || ORIG_REF_NAME==dma_axis_ip_example_xbar_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_ps7_0_axi_periph_0/dma_axis_ip_example_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_ps7_0_axi_periph_0 || ORIG_REF_NAME==dma_axis_ip_example_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_rst_ps7_0_100M_0/dma_axis_ip_example_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_rst_ps7_0_100M_0 || ORIG_REF_NAME==dma_axis_ip_example_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_example_0_0/dma_axis_ip_example_example_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_example_0_0 || ORIG_REF_NAME==dma_axis_ip_example_example_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_clk_wiz_0_0/dma_axis_ip_example_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_clk_wiz_0_0 || ORIG_REF_NAME==dma_axis_ip_example_clk_wiz_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_xlconstant_0_0/dma_axis_ip_example_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_xlconstant_0_0 || ORIG_REF_NAME==dma_axis_ip_example_xlconstant_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_fifo_generator_0_0/dma_axis_ip_example_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_fifo_generator_0_0 || ORIG_REF_NAME==dma_axis_ip_example_fifo_generator_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_util_vector_logic_0_3/dma_axis_ip_example_util_vector_logic_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_util_vector_logic_0_3 || ORIG_REF_NAME==dma_axis_ip_example_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_read_from_fifo_0_0/dma_axis_ip_example_read_from_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_read_from_fifo_0_0 || ORIG_REF_NAME==dma_axis_ip_example_read_from_fifo_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_proc_sys_reset_0_0/dma_axis_ip_example_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_proc_sys_reset_0_0 || ORIG_REF_NAME==dma_axis_ip_example_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_c_counter_binary_0_0/dma_axis_ip_example_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_c_counter_binary_0_0 || ORIG_REF_NAME==dma_axis_ip_example_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_xlslice_0_0/dma_axis_ip_example_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_xlslice_0_0 || ORIG_REF_NAME==dma_axis_ip_example_xlslice_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_system_ila_0_2/dma_axis_ip_example_system_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_system_ila_0_2 || ORIG_REF_NAME==dma_axis_ip_example_system_ila_0_2} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_util_vector_logic_1_0/dma_axis_ip_example_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_util_vector_logic_1_0 || ORIG_REF_NAME==dma_axis_ip_example_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_0_0/dma_axis_ip_example_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_axi_gpio_0_0 || ORIG_REF_NAME==dma_axis_ip_example_axi_gpio_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_Quad_0_0/dma_axis_ip_example_Quad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_Quad_0_0 || ORIG_REF_NAME==dma_axis_ip_example_Quad_0_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_axi_gpio_1_0 || ORIG_REF_NAME==dma_axis_ip_example_axi_gpio_1_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_util_vector_logic_5_0/dma_axis_ip_example_util_vector_logic_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_util_vector_logic_5_0 || ORIG_REF_NAME==dma_axis_ip_example_util_vector_logic_5_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_util_vector_logic_2_0/dma_axis_ip_example_util_vector_logic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_util_vector_logic_2_0 || ORIG_REF_NAME==dma_axis_ip_example_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_0/dma_axis_ip_example_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_auto_pc_0 || ORIG_REF_NAME==dma_axis_ip_example_auto_pc_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_ds_0/dma_axis_ip_example_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_auto_ds_0 || ORIG_REF_NAME==dma_axis_ip_example_auto_ds_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_1/dma_axis_ip_example_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_auto_pc_1 || ORIG_REF_NAME==dma_axis_ip_example_auto_pc_1} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_2/dma_axis_ip_example_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_auto_pc_2 || ORIG_REF_NAME==dma_axis_ip_example_auto_pc_2} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_s00_mmu_0/dma_axis_ip_example_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_s00_mmu_0 || ORIG_REF_NAME==dma_axis_ip_example_s00_mmu_0} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_3/dma_axis_ip_example_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_auto_pc_3 || ORIG_REF_NAME==dma_axis_ip_example_auto_pc_3} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_4/dma_axis_ip_example_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_auto_pc_4 || ORIG_REF_NAME==dma_axis_ip_example_auto_pc_4} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_s00_mmu_1/dma_axis_ip_example_s00_mmu_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_s00_mmu_1 || ORIG_REF_NAME==dma_axis_ip_example_s00_mmu_1} -quiet] -quiet

# IP: bd/dma_axis_ip_example/ip/dma_axis_ip_example_s01_mmu_0/dma_axis_ip_example_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_axis_ip_example_s01_mmu_0 || ORIG_REF_NAME==dma_axis_ip_example_s01_mmu_0} -quiet] -quiet

# XDC: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.gen/sources_1/bd/dma_axis_ip_example/dma_axis_ip_example_ooc.xdc
