# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0.xci
# IP: The module: 'dma_axis_ip_example_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0.xci
# IP: The module: 'dma_axis_ip_example_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/w/inkjet_3d/MP113_FPGA/Design_1/myproj/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_axi_gpio_1_0/dma_axis_ip_example_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
